export interface Project {
  id: string;
  title: string;
  creator: string;
  age: number;
  location: string;
  category: "Automation" | "AI" | "IoT" | "API" | "Other";
  description: string;
  hours: number;
  concepts: string[];
  documentation: string;
}

export const projects: Project[] = [
  {
    id: "1",
    title: "Email Auto-Responder",
    creator: "Amara O.",
    age: 16,
    location: "Nigeria",
    category: "Automation",
    description: "Automatically categorizes incoming emails and sends contextual responses using Gmail API and a custom ruleset built with Make.com.",
    hours: 12,
    concepts: ["Gmail API", "Make.com", "Webhooks", "Conditional Logic"],
    documentation: "This project automates email handling by connecting Gmail to Make.com. Incoming emails are parsed, categorized by keywords, and routed to different response templates. The system handles support queries, scheduling requests, and newsletter signups automatically.\n\nThe workflow was built using Make.com's drag-and-drop interface with custom filters and multi-branch routing. Each branch triggers a different Gmail template and logs the interaction to a connected Airtable database for tracking."
  },
  {
    id: "2",
    title: "Plant Watering Robot",
    creator: "Jake M.",
    age: 15,
    location: "USA",
    category: "IoT",
    description: "An Arduino-based system that monitors soil moisture and automatically waters plants when levels drop below a threshold.",
    hours: 18,
    concepts: ["Arduino", "Sensors", "C++", "Automation Logic"],
    documentation: "Built with an Arduino Uno and a soil moisture sensor, this project reads soil levels every 30 minutes and activates a small water pump when the moisture drops below 30%. A green LED indicates watering in progress.\n\nThe code was written in C++ using the Arduino IDE. A small relay module controls the pump power, and all readings are logged to a serial monitor for debugging."
  },
  {
    id: "3",
    title: "Slack Daily Digest Bot",
    creator: "Priya K.",
    age: 17,
    location: "India",
    category: "API",
    description: "A Slack bot that aggregates messages from multiple channels and sends a daily digest summary every morning at 9am.",
    hours: 10,
    concepts: ["Slack API", "Node.js", "Cron Jobs", "API Integration"],
    documentation: "This bot uses the Slack API to read messages from specified channels and compile them into a formatted summary. It runs on a cron schedule via a hosted Node.js script and posts the digest to a designated channel at 9am.\n\nThe project taught me about OAuth token management, rate limiting, and structuring async API calls in Node.js."
  },
  {
    id: "4",
    title: "AI Recipe Generator",
    creator: "Luca R.",
    age: 16,
    location: "Italy",
    category: "AI",
    description: "Enter ingredients you have at home and get a custom recipe generated by GPT-4, then saved to a personal cookbook database.",
    hours: 14,
    concepts: ["OpenAI API", "Airtable", "Prompt Engineering", "Web Frontend"],
    documentation: "This web app takes a list of ingredients from the user and sends them to the OpenAI API with a carefully crafted prompt to generate a recipe. The recipe is then automatically saved to an Airtable base organized by cuisine type.\n\nI learned how to engineer prompts to get consistent structured output and how to parse JSON responses from the API."
  },
  {
    id: "5",
    title: "Social Media Scheduler",
    creator: "Sofia B.",
    age: 17,
    location: "Brazil",
    category: "Automation",
    description: "A no-code automation that pulls content from a Google Sheet and schedules posts across Twitter, Instagram, and LinkedIn.",
    hours: 8,
    concepts: ["Make.com", "Google Sheets", "Social APIs", "Scheduling"],
    documentation: "Using Make.com, I connected a Google Sheets content calendar to Twitter, Instagram, and LinkedIn APIs. The automation checks the sheet for posts scheduled for the current day and publishes them at the right time.\n\nThe project handles image uploads, character limits per platform, and tracks published status back in the sheet."
  },
  {
    id: "6",
    title: "Home Security Camera Alert",
    creator: "Kwame A.",
    age: 15,
    location: "Ghana",
    category: "IoT",
    description: "A Raspberry Pi camera system that detects motion and sends WhatsApp alerts with a photo snapshot.",
    hours: 20,
    concepts: ["Raspberry Pi", "Python", "Motion Detection", "WhatsApp API"],
    documentation: "This project uses a Raspberry Pi with a camera module and Python's OpenCV library to detect motion. When movement is detected, it captures a photo and sends it via the WhatsApp Business API to a specified number.\n\nI set up the motion detection algorithm to only trigger during certain hours and added a cooldown to avoid spam alerts."
  },
  {
    id: "7",
    title: "Crypto Price Notifier",
    creator: "Yuki T.",
    age: 16,
    location: "Japan",
    category: "API",
    description: "Monitors cryptocurrency prices via an API and sends Telegram notifications when prices cross custom thresholds.",
    hours: 7,
    concepts: ["CoinGecko API", "Telegram Bot API", "Python", "Polling"],
    documentation: "This Python script polls the CoinGecko API every 5 minutes to check Bitcoin and Ethereum prices. When the price crosses user-defined thresholds, it triggers a Telegram bot to send an alert message with the current price and percentage change.\n\nI learned about API polling, rate limits, and building simple Telegram bots with the python-telegram-bot library."
  },
  {
    id: "8",
    title: "AI Study Flashcard Maker",
    creator: "Nia C.",
    age: 14,
    location: "UK",
    category: "AI",
    description: "Upload any PDF or text and the app automatically generates Anki-compatible flashcards using AI summarization.",
    hours: 16,
    concepts: ["OpenAI API", "PDF Parsing", "Anki Format", "Python"],
    documentation: "This tool takes a PDF or plain text file, extracts the content using PyPDF2, and sends chunks to the OpenAI API to generate question-and-answer flashcard pairs. The output is formatted as a CSV that can be imported directly into Anki.\n\nThe project required careful prompt engineering to get well-structured Q&A pairs and chunking the text to stay within API context limits."
  }
];
